import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/Header";
import Classes from "./components/Classes";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Gym | Fitness",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-bodyFont bg-bodyColor">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
